In [2]:
# header
import numpy as np
import math

Bài 1

In [44]:
bang_diem = np.array([[7. ,8. ,9. ,5.],
                      [8., 7., 4., 6.],
                      [7., 5., 8., 6.],
                      [9., 9., 8., 7.],
                      [10., 8., 9., 8.]])
hoc_sinh = np.array(["A", "B", "C", "D"])

In [48]:
def DiemTrungBinh(diem_hs: np.ndarray) -> float:
    diem_tb: float = 0

    for i in range(diem_hs.size):
        diem_tb = diem_tb + ((diem_hs[i] * (i + 1) * 10.0) / 100.0)

    return diem_tb

In [49]:
for diem_hs, hs in zip(bang_diem, hoc_sinh):
    diem_tb: float = round(DiemTrungBinh(diem_hs), 2)

    status: str = "dau" if (diem_tb >= 5.0) else "rot"

    print(f"Diem trung binh cua hoc sinh {hs} la {diem_tb} va hoc sinh {hs} {status}")

Diem trung binh cua hoc sinh A la 7.0 va hoc sinh A dau
Diem trung binh cua hoc sinh B la 5.8 va hoc sinh B dau
Diem trung binh cua hoc sinh C la 6.5 va hoc sinh C dau
Diem trung binh cua hoc sinh D la 7.9 va hoc sinh D dau


Bài 2

In [55]:
matranA = np.random.randint(0, 11, size=(3, 3))
matranB = np.random.randint(0, 11, size=(3, 3))
print(matranA)
print(matranB)

[[ 7  0 10]
 [ 3  1  9]
 [ 8  9  7]]
[[6 0 0]
 [4 1 7]
 [7 6 6]]


In [56]:
normVec1OfA: float = np.linalg.norm(matranA[0])
normVec3OfB: float = np.linalg.norm(matranB[2])

so_sanh: str = "Vector 1 ma tran A lon hon Vector 3 ma tran B" if (normVec1OfA > normVec3OfB) else "Vector 3 ma tran B lon hon Vector 1 ma tran A"

print(so_sanh)

Vector 1 ma tran A lon hon Vector 3 ma tran B


In [57]:
matranC = np.add(matranA, matranB)
matranC

array([[13,  0, 10],
       [ 7,  2, 16],
       [15, 15, 13]])

In [58]:
matranD = np.subtract(matranA, matranB)
matranD

array([[ 1,  0, 10],
       [-1,  0,  2],
       [ 1,  3,  1]])

In [59]:
matranE = matranA @ matranB
matranE

array([[112,  60,  60],
       [ 85,  55,  61],
       [133,  51, 105]])

Bài 3

In [82]:
vec = np.random.randint(0, 100, size=(21,))
vec

array([ 1, 97, 82, 60,  3, 19, 52, 97, 25, 29, 28, 90,  7, 97, 53, 19,  4,
       95, 25, 90, 66])

In [83]:
u, v, w = np.split(vec, 3)
print(u)
print(v)
print(w)

[ 1 97 82 60  3 19 52]
[97 25 29 28 90  7 97]
[53 19  4 95 25 90 66]


In [84]:
# element-wise multiplication
u*v

array([  97, 2425, 2378, 1680,  270,  133, 5044])

In [85]:
# dot product
v.dot(w)

17674

In [86]:
u.shape

(7,)

In [88]:
np.transpose(u)

array([ 1, 97, 82, 60,  3, 19, 52])

**Nhận xét**: Ta thấy $u$ và $u^T$ tương có shape tương tự như nhau do vector khi chuyển vị lại thì vẫn là 1 vector như cũ. Nếu muôn khác biệt ta cần biến 1D vector thành column vector trong 2D, khi đó việc chuyển vị sẽ thành row vector. 