In [1]:
import numpy as np
import scipy

In [6]:
matran1 = np.mat([[3,4],
                  [5,6]])
matran1

matrix([[3, 4],
        [5, 6]])

In [7]:
matran1.I

matrix([[-3. ,  2. ],
        [ 2.5, -1.5]])

In [8]:
matran1.T

matrix([[3, 5],
        [4, 6]])

In [10]:
np.tril(matran1)

array([[3, 0],
       [5, 6]])

In [11]:
np.triu(matran1)

array([[3, 4],
       [0, 6]])

In [12]:
np.diag(matran1)

array([3, 6])